spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: achraf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  #database-platform: org.hibernate.dialect.MySQLDialect

app:
  security:
    jwt:
      # https://seanwasere.com/generate-random-hex/
      # 256 bit 32 Byte Hex
      secret-key: d15230087c7875d3a253fd32f7418484734cb32e813eef58ac594467f1488ce8
      expiration: 18000000 # to have it valid for a day use: 86400000 ms
      refresh-token:
        expiration: 180000000